apiVersion: apps/v1
kind: Deployment
metadata:
  name: lookup-server-deployment
spec:
  selector:
    matchLabels:
      app: lookup-server
  replicas: 1
  template:
    metadata:
      labels:
        app: lookup-server
    spec:
      containers:
      - name: lookup-server
        image: andreisfrent/ahv-defender:lookup-server
        imagePullPolicy: Always
        ports:
        - containerPort: 12000
      imagePullSecrets:
      - name: regcred

