apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: andreisfrent/ahv-defender:web-server
        ports:
        - containerPort: 7835
      imagePullSecrets:
      - name: regcred
